Feature/admin trainer
Entrenarme/SpaceUI pull request #33
Opened 2018-11-22 14:47 UTC by talensjr

2018-11-23 12:04 UTC, angabar commented on src/core/Form/RadioButton/index.tsx
>    input[type='radio'] {
Igual que en el checkbox... estaria be que fora pointer

2018-11-23 12:05 UTC, angabar commented on src/core/Form/Checkbox/Toggle.tsx
> +const Label = styled.label<LabelProps>`
Te costaría molt posar un cursor: pointer en el checkbox i el text? Per a que el element parega mes clikable, la resta esta identic al diseny, perfecte ;)

2018-11-23 12:09 UTC, angabar commented on src/core/Slider/DaySlider.tsx
>    static Slide = (props: SlideProps) => (
No se masa be si es un problema de este component o de algun altre... pero en algunes resolucions els dies del slider no aplegen al final... disant molt de espai buit

![144](https://user-images.githubusercontent.com/4190084/48942717-01535d80-ef21-11e8-9388-4eb1d4199db6.png)

Resolucions en les que me pasa (soles width):
* 1024px
* 768px
* 425px
* 320px (en esta es un poc menos)

La resta esta perfecte, en diseny i en funcionalitat

2018-11-23 14:43 UTC, angabar requested changes

2018-11-23 14:43 UTC, angabar commented on src/core/Form/RadioButton/index.tsx
>    input[type='radio'] {
Te costaría molt posar un cursor: pointer? Per a que el element parega mes clikable, la resta esta identic al diseny, perfecte ;)

2018-11-23 14:46 UTC, angabar requested changes

2018-11-23 14:46 UTC, angabar commented on src/core/Form/Checkbox/Toggle.tsx
> +  input[type='checkbox'] {
Podries posar en este un cursor pointer tambe?

2018-11-23 14:46 UTC, angabar commented on src/core/Form/Checkbox/index.tsx
> +const Label = styled.label`
Te costaría molt posar un cursor: pointer en el checkbox i el text? Per a que el element parega mes clikable, la resta esta identic al diseny, perfecte ;)

2018-11-23 14:46 UTC, angabar commented on src/core/Slider/DaySlider.tsx
>    render() {
No se masa be si es un problema de este component o de algun altre... pero en algunes resolucions els dies del slider no aplegen al final... disant molt de espai buit

![144](https://user-images.githubusercontent.com/4190084/48942717-01535d80-ef21-11e8-9388-4eb1d4199db6.png)

Resolucions en les que me pasa (soles width):
* 1024px
* 768px
* 425px
* 320px (en esta es un poc menos)

La resta esta perfecte, en diseny i en funcionalitat

2018-11-26 07:58 UTC, talensjr commented on src/core/Slider/DaySlider.tsx
>    render() {
A la espera del que diga Damián ací.

2018-11-26 07:58 UTC, talensjr commented on src/core/Form/Checkbox/index.tsx
> +const Label = styled.label`
Done

2018-11-26 07:58 UTC, talensjr commented on src/core/Form/Checkbox/Toggle.tsx
> +  input[type='checkbox'] {
Done

2018-11-26 07:58 UTC, talensjr commented on src/core/Form/RadioButton/index.tsx
>    input[type='radio'] {
Done

2018-11-26 10:01 UTC, merged